---
name: Docker Build Check

on:
  pull_request:
    branches:
      - master
      - develop

permissions: { }

jobs:
  docker-build:
    name: Validate Docker Build
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: read
        statuses: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile -t go-cdn .
